---
title: 'Gráfico II: Taxa de suicídio por grupo de renda'
author: "Tiago da Silva"
date: "12/06/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(scales)
library(cowplot)
library(ggthemes)
library(directlabels)
```

# Lendo os dados.

```{r, fig.width = 11, fig.height = 8}

continents <- carregar("continents.txt", "csv2") %>% rename(country = Country) %>%
  mutate(country = ifelse(country == "US", "United States", country)) #A função carregar() foi definida em graficoI.Rmd.

gdp <- carregar("GDP.csv")


suicide <- carregar("master.csv") %>% rename(country = ï..country) %>%
  inner_join(continents) %>%
  rename(continent = Continent, gcap = gdp_per_capita....) %>%
  inner_join(gdp, by = c("country" = "TableName")) %>%
  mutate(IncomeGroup = as.factor(IncomeGroup))


```


```{r, fig.width = 11, fig.height = 8}



suicide %>%
  filter(year == 2010) %>%
  group_by(country, continent, HDI.for.year) %>%
  summarise(suicide.rate = sum(suicides_no)/sum(population)) %>%
  ungroup() %>%
  ggplot(aes(x = HDI.for.year, y = suicide.rate)) +
  geom_point() +
  labs(x = "Índice de desenvolvimento humano", y = "Taxa de suicídios (por cem mil habitantes)") +
  scale_y_continuous(labels = function(b){paste0(b*10^5)}) +
  theme_bw() +
  theme(axis.title.x = element_text(size = 13),
        axis.title.y = element_text(size = 13))-> hdi_suicide

save_pdf_png(plot = hdi_suicide, width = 8, height = 8, diretorio = "C:/Users/tiago/OneDrive/Documentos/aed-projeto.suicidio/output",
             nome = "hdi_suicide")

suicide %>%
  mutate(IncomeGroup = factor(IncomeGroup, levels = c("Lower middle income", "Upper middle income", "High income"))) %>%
  group_by(country, year, HDI.for.year, IncomeGroup, continent) %>%
  summarise(suicide.rate = sum(suicides_no)/sum(population)) %>%
  ungroup() %>%
  filter(year == 2010,
         !suicide.rate == 0) %>%
  ggplot() +
  geom_boxplot(aes(x = IncomeGroup, y = suicide.rate, fill = IncomeGroup)) +
  scale_y_sqrt(name = "Taxa de suicídios (por cem mil habitantes)",
               labels = function(b){paste0(b * 10^5)}) +
  theme_bw() +
  scale_fill_manual(values = c("#42BA30",
                                "#BA5A1E",
                                "#190BBA"),
                    labels = c(expression("Renda média baixa"^1), expression("Renda média alta"^2), expression("Alta renda"^3))
                    ) +
        theme(legend.position = c(0.5, 0.96),
              legend.direction = "horizontal",
              axis.title.x = element_blank(),
              axis.text.x = element_blank(),
              axis.ticks.x = element_blank(),
              legend.title = element_blank(),
              legend.text = element_text(size = 13),
              axis.text.y = element_text(size = 13),
              axis.title.y = element_text(size = 13.5, face = "italic"),
              plot.title = element_text(hjust = .5, size = 16, family = "mono", face = "bold"),
              panel.grid.minor.y = element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.major.y = element_line(linetype = 2),
              plot.caption = element_text(hjust = 0, size = 9.5)) +
  ggtitle("Taxa de suicídios por grupo de renda") +
  labs(captions = "PIB per capta (US$): 1. 1.036 - 4.085; 2. 4.086 - 12.615; 3. > 12.616. 
       \nDados do Banco Mundial e da Organização Mundial da Saúde.") -> boxplot_incomegroup



boxplot_incomegroup



save_pdf_png(plot = boxplot_incomegroup,
             nome = "boxplot_suicidio",
             diretorio = "C:/Users/tiago/OneDrive/Documentos/aed-projeto.suicidio/output",
             width = 11, height = 8)


#Asia, Africa, Europe, North America, South America, Oceania



population <- data.frame(continent = c("Africa", "Asia", "Europe", "North America", "Oceania", "South America"), pop = c(1216130000, 4581757408, 738849000, 579024000, 38304000, 422535000))

population

suicide %>%
  filter(year == 2010) %>%
  group_by(continent) %>%
  summarise(sum = sum(population)) %>%
  ungroup() %>%
  inner_join(population, by = c("continent" = "continent")) %>%
  mutate(ratio = sum/pop * 100)


```
